### ISSUE TITLE
Compatible with sfDoctrineGuardPlugin

### ISSUE THREAD

**Issue by dator-zz** [chok/sfMelodyPlugin#1]
make sfMelodyPlugin works with sfMelody to add another possibility to create an account :)

no ?

**Comment by chok** [comment]
Thanks  for your interest :)

In fact, sfMelody already create an account automaticaly if you don' t set create_user: false in the app.yml :p.

If you connect with Facebook for example, the username is  "Facebook_{fuid}"...

Is that you want to say ?

**Comment by dator-zz** [comment]
Not exactly ^^

Just add the possibility to create an account and login with a standart method (not by a service) 

:)

**Comment by chok** [comment]
You can log an user with a standard method by any way you want. After logged in, if you connect to a service the connected user have authorization requested. 

The connected user is linked to service requested.

I have given the right answer ? :s

**Comment by chok** [comment]
Closed... again damned Github crash
