### ISSUE TITLE
Make ORM Adapter more extensible

### ISSUE THREAD

**Issue by passkey1510** [chok/sfMelodyPlugin#18]
In our project, we have an extra table which stores user profile information such as email, fullname...
It should be better to have the ORM Adapter configurable via app.yml so that ones can extends sfMelodyDoctrineOrmAdapter to override findByMelody function

**Comment by chok** [comment]
You're right. Not enough generic yet.

I haven't enough time yet. But it's in the TODO List :-)

**Comment by chok** [comment]
You can also contribute ;-)

**Comment by chok** [comment]
Argl I've closed this issue. I don't know how reopen :(
