### ISSUE TITLE
Display parameter for Facebook

### ISSUE THREAD

**Issue by tobiassjosten** [chok/sfMelodyPlugin#23]
By default, the display parameter when authenticating with Facebook is set to "page". I need this to be "touch" for it to work properly with mobile devices. What is the best way to set this?

http://www.facebook.com/connect/uiserver.php?app_id=166599816703806&method=permissions.request&display=page&next=http://local.klaralifvet.se/frontend_dev.php/access/facebook&response_type=code&fbconnect=1&perms=email

versus

http://www.facebook.com/connect/uiserver.php?app_id=166599816703806&method=permissions.request&display=touch&next=http://local.klaralifvet.se/frontend_dev.php/access/facebook&response_type=code&fbconnect=1&perms=email

**Comment by chok** [comment]
Yes Added to theTodo list :)

**Comment by tobiassjosten** [comment]
Any preferences on where and how to add it? I would love to give it a whack and contribute to this plugin.

**Comment by chok** [comment]
:) Just add a test to add 'display' parameter to call paramaters in the sfFacebookMelody. And just add it tot your config.

Better Idea ?

**Comment by tobiassjosten** [comment]
Fixed with PR in #35.
