### ISSUE TITLE
"The route "mymodule_connect" does not exist."

### ISSUE THREAD

**Issue by czaku** [chok/sfMelodyPlugin#32]
well maybe i am not familiar enough with symfony, but I did everything from readme file and the link_to makes the error above, the route does not exist, i need to connect to facebook...

**Comment by chok** [comment]
Do you have created a route named mymodule_connect in routing.yml of your app ?

**Comment by czaku** [comment]
nope, there is nothing about that in readme, i am quite new in symfony, read about routing but still sfMelody is missing a lot of documentation, can you help me with that?

**Comment by czaku** [comment]
its all about callback i think, i could route mymodule_connect to access/facebook but that then?

**Comment by chok** [comment]
Sorry for documentation :D

You have a sample project here : https://github.com/chok/Melody-Doctrine-test

The routing file : https://github.com/chok/Melody-Doctrine-test/blob/master/apps/melody/config/routing.yml

You have to put a routing rule like that : 

mymodule_connect:
  url: /connect
  param: { module: melody, action: connect }

**Comment by czaku** [comment]
thanks a lot ;)
