### ISSUE TITLE
connection with facebook makes 'NULL' user in database

### ISSUE THREAD

**Issue by czaku** [chok/sfMelodyPlugin#33]
when I use melody test like app you provided in last issue it makes an empty user in database, no email, first name and last name is empty...

**Comment by chok** [comment]
Yes It already exists an issue about that. I'll try to fix this as soon as possible. It's in the user creation part. You can also fix it if you want :)

**Comment by czaku** [comment]
f**k i need it working for tomorrow :P

**Comment by chok** [comment]
Argl ! I'll try to fix today. I'll inform you when done.

**Comment by czaku** [comment]
give me some tips I could try to help, I am just learning symfony, could be a nice try for me ;)

**Comment by chok** [comment]
:) It's in this file : https://github.com/chok/sfMelodyPlugin/blob/master/modules/sfMelody/lib/BasesfMelodyActions.class.php. We have to check if the acces token is correct.

**Comment by czaku** [comment]
well in database my token has both  key and secret that are NULL :/ for the user that is NULL as well

**Comment by chok** [comment]
Oups ! It's here sfMelodyUserFactory.class.php.

A quick fix is to set redirect_register in your config and test the user created.

And save the user if it's correct

**Comment by czaku** [comment]
all:
  melody:
    create_user: false
    redirect_register: false
    facebook:
      key: xxx
      secret: xxx
      callback: "@melody_facebook"
      scope: [email]
      aliases:
        friends: me/friends
      user:
        email_address: 
          call: me
          path: email 
          key: true
        username: 
          call: me
          path: id
          prefix: Facebook_
        first_name:
          call: me
          path: first_name
        last_name: 
          call: me
          path: last_name

still user and token NULL, whether I save the user or not - of course instead of xxx i have my keys there...

**Comment by chok** [comment]
redirect_register has to be a route like callback :p

in your action :
$user = unserialize($this->getUser()->getAttribute('melody_user'));
$melody = unserialize($this->getUser()->getAttribute('melody'));

You can check if user have correct fields

**Comment by chok** [comment]
if you don't want to create user it' create_user: false et not createuser

**Comment by chok** [comment]
Haha you don't read documentation :

Before saving the user, if you specify redirect_register with a valid routing rule, you can redirect the workflow to your action.

In this case, you can retrieve the user created but not saved :

```
unserialize($this->getUser()->getAttribute('melody_user'))
```

And the melody :

```
unserialize($this->getUser()->getAttribute('melody'))
```

:p

**Comment by czaku** [comment]
sorry dont be angry with me :P i will try to set this and tell you if it works later :P the _ in create_user was deleted by github :P

**Comment by czaku** [comment]
well i really dont understand that part :P maybe i am to new with that... i just need to allow an access for a facebook user (which is working) and then to put into db user fbid email last and first name, if he visits an app again to have him recognized as existing in database (i am making a quiz so he has to answer few questions each question new week)

**Comment by chok** [comment]
1. Create a ruting rule like callback  :
   redirect_register:
   url: /redirect-register
   param: { module: some_module, action: redirect }
2. put in your melody config with the key redirect_register 
3. In the module some_module, you have to create the action redirect.
4. You retrieve user in this action and you check field of the user if correct you save it

If you connect many times with fb, melody retrieve the user with key in your config (key: true) you have specified it's automatic :)

More clear ?

**Comment by czaku** [comment]
trying to understand ;) i made routing redirect_register: url: /redirect-register param: { module: main, action: redirect }
in config i put redirect_register: @redirect_register

then i make an action
  public function executeRedirect(sfWebRequest $request)
  {
    $user = unserialize($this->getUser()->getAttribute('melody_user'));
    $melody = unserialize($this->getUser()->getAttribute('melody'));
  }

and something is missing like saving user etc.. my key is an email like in an example but maybe i can change to fbid:

user:
        email_address: 
          call: me
          path: email 
          key: true
        username: 
          call: me
          path: id
          #prefix: Facebook_
        first_name:
          call: me
          path: first_name
        last_name: 
          call: me
          path: last_name

**Comment by chok** [comment]
email is a good key and you can share it with other providers if available.

In your redirect action you have to check user fields and save if this is you want like:

```
if (!is_null($user->getFirstName())
{
  $user->save();
}
```

**Comment by czaku** [comment]
id doesnt create any user now :/ even a NULL one, god I am stupid :P

**Comment by chok** [comment]
Can you post your code ?

**Comment by czaku** [comment]
well i made route, thats my actions:

class mainActions extends sfActions
{

  public function executeConnect(sfWebRequest $request)
  {
    $this->getUser()->connect('facebook');
  }

  public function executeFacebook(sfWebRequest $request)
  {

```
$fb_melody = $this->getUser()->getMelody('facebook');

$this->me = $fb_melody->getMe(null, array('fields' => 'picture', 'size' => 'large'));
$this->friends = $fb_melody->getFriends(array('friends' => 'me/friends'));
```

  }

  public function executeIndex(sfWebRequest $request)
  {
    $this->questions = Doctrine_Core::getTable('Question')
      ->createQuery('a')
      ->execute();
  }

  public function executeRedirect(sfWebRequest $request)
  {
    $user = unserialize($this->getUser()->getAttribute('melody_user'));
    $melody = unserialize($this->getUser()->getAttribute('melody'));
    if (!is_null($user->getFirstName())) {
        $user->save();
    }
  }

}

**Comment by czaku** [comment]
is there any way to talk to you on any IM ?

**Comment by chok** [comment]
:s 

$this->questions = Doctrine_Core::getTable('Question')
->createQuery('a')
->execute(); 
=> $this->questions = QuestionTable::getInstance()->findAll(); 
no ?

it's just an example for first name. you can take the email_address.

You have my Gmail address on my profile ;-)

**Comment by czaku** [comment]
well dont look at index right now, it could be empty, its not connected with user for now... i need a user to exist in database ;) previoulsly before i made that redirect etc i had a null user now i dont have any...

**Comment by chok** [comment]
It's normal if create at each time a null user.

Post your log about Oauth to see the problem

**Comment by czaku** [comment]
sent you an email...

**Comment by czaku** [comment]
this is the fix (i think is not very secure): 

sfOAuth.class.php - call() method - two lines after the comment added

```
protected function call($url, $url_params = null, $post_params = null, $method = 'POST') {
    $ci = curl_init();

    //added by czaku for sfMelodyPlugin compatibility
    curl_setopt($ci, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ci, CURLOPT_SSL_VERIFYHOST, 2);


    if(is_array($url_params) && count($url_params) > 0) {
        $url_params = http_build_query($url_params);
    }
```

....
....

}

further info:

http://stackoverflow.com/questions/2875464/facebook-connect-php-sdk-curl-peer-ssl-verification-error
http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/

**Comment by chok** [comment]
Aaaaargl !

OAuth is based on the security of ssl, if you do that you loose the security of OAuth2.

If you want this more secure, you have to download the certificate of facebook with firefox for example.

And you put this instead :

curl_setopt($this->curl, CURLOPT_SSL_VERIFYPEER, true);
curl_setopt($this->curl, CURLOPT_SSL_VERIFYHOST, true);
curl_setopt($this->curl, CURLOPT_CAINFO, '/path/to/certificate/you/download.crt');

Keep in mind Melody does'nt work anymore for other provider than facebook

**Comment by czaku** [comment]
yep i get it, I read two links you provided and I know I have to download this facebook certifivate ;) for now i use false for testing ;) later i will think about securing this app better ;) thanks again!
