### ISSUE TITLE
Negative response from OAuth provider

### ISSUE THREAD

**Issue by igorzoriy** [chok/sfMelodyPlugin#40]
Hello. I integrated your plugin on my site and find next trouble. When I try to connect to Facebook (or other provider), the plugin redirected me on facebook's special page. If I click "Don't Allow" button, the plugin still try to create user. Is this bug or feature?

**Comment by chok** [comment]
Hi,

Definitivley a bug ! The fail back is not right managed and have to fix.

Thanks to post this issue :) You can also contribute by fixing that :D
