### ISSUE TITLE
Connect/Authorize Popup Window

### ISSUE THREAD

**Issue by mWardi** [chok/sfMelodyPlugin#42]
Hello, 
Is there any way to open a new window for the authorize/connect url instead of redirecting the user in the same page.
When trying to connect to Facebook or Twitter or authorizing the app, the actual behavior is to load the connect/authorize page in the same actual page. I was looking for a way to open a new window for that, without leaving the site, but no clue. 

Thanks for the plugin :)

**Comment by chok** [comment]
Hi,

I never use it but you can use the display parameter from facebook  added in this commit https://github.com/chok/sfMelodyPlugin/commit/dd568d8acb680e2f276e1c85818bf4c161f2404e

You have to open a popup and give this parameter as popup
