### ISSUE TITLE
Class sfOAuth2 not found

### ISSUE THREAD

**Issue by JunniH** [chok/sfMelodyPlugin#53]
I've integrated the sfMelodyPlugin into my Symfony 1.4.x project, to implement Facebook Connect (Authentication).

The plugin shows me the Facebook Login & app approval windows, but after submitting I get the following error:

Fatal error: Class 'sfOAuth2' not found in /Users/Junni/Projects/gifthings/plugins/sfMelodyPlugin/lib/melody/base/sfMelody2.class.php on line 2

Class sfMelody2 extends sfAuth2, but it isn't included in the plugin, nor is it in the sfPropelOAuthPlugin. Am I missing something?

Thanks in advance!

**Comment by chok** [comment]
Hi,

This class is in the Base submodule of sfPropelOAuth. Did you initialize submodules ?

**Comment by JunniH** [comment]
Hi Maxime,

Thanks for you answer and sorry for my late reply…I was on holiday.
I did initialize the submodule but got another missing class. In the meanwhile I've used the Facebook API to get the needed results :)

Groetjes,
Junior

## 

Junior Hemelaer
Founder CryptoNet.be

**Comment by chok** [comment]
Ok, so I close the issue :)

Maxime
